### ISSUE TITLE
Make UI theme use any syntax theme colours

### ISSUE THREAD

**Issue by gilbertohasnofb** [monsieurluge/atom-distraction-free-syntax#2]
Hi, I'm opening an issue here as your repository `atom-distraction-free-ui-theme` does not have an Issues tab. 

I really like your UI theme, but I find it a pity that the colours are hard coded in it and, thus, it works well only with the syntax theme you provide. Would you consider updating your UI theme so that it borrows the colours from whatever syntax theme is being used? See for instance how Atom Material handles that.

**Comment by monsieurluge** [comment]
Hi,

Thanks for notifying me that the issues tab was not displayed for the UI theme repo. I fixed that.

I don't know how to do a proper syntax theme integration so I'll take a look to the Material theme. Thanks for the idea.

**Comment by monsieurluge** [comment]
I'll close this issue and copy your message to a new issue, in the proper repo ;)
